# Copyright 2023 Red Hat, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[amsclient]
url = ""
client_id = ""
client_secret = ""
page_size = 100

[server]
address = ":8081"
api_dbg_prefix = "/api/dbg/"
api_v1_prefix = "/api/v1/"
api_v2_prefix = "/api/v2/"
api_v1_spec_file = "server/api/v1/openapi.json"
api_v2_spec_file = "server/api/v2/openapi.json"
debug = true
auth = true
auth_type = "xrh"
use_https = false
enable_cors = true
enable_internal_rules_organizations = false
internal_rules_organizations = []
log_auth_token = true
org_clusters_fallback = true
use_rbac = false

[services]
aggregator = "http://localhost:8080/api/insights-results-aggregator/v1/"
content = "http://localhost:8082/api/v1/"
groups_poll_time = "60s"
content_directory_timeout = "1s"

[setup]
internal_rules_organizations_csv_file = ""

[metrics]
namespace = "smart_proxy"

[redis]
database = 0
endpoint = "localhost:6379"
password = ""
timeout_seconds = 30

[rbac]
url = "https://console.redhat.com/api/rbac/v1"
enforce = false
