title: Insights Results Smart Proxy
description: Smart Proxy service for Openshift insights results
baseurl: "/insights-results-smart-proxy"
url: "https://redhatinsights.github.io"
repository: "RedHatInsights/insights-results-smart-proxy"

heading_anchors: true
search_enabled: false

aux_links:
  "Github repository":
    - "https://github.com/RedHatInsights/insights-results-smart-proxy"

footer_content: "Copyright &copy; 2020 Red Hat, Inc.</a>"

# Build settings
markdown: kramdown
# remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/

keep_files:
  - .gitleaks.toml
